spring.application.name=InventoryManagement
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=dev
spring.datasource.password=Madarapb100
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.Type=TRACE

management.endpoints.web.exposure.include=health,info,beans,mapping,env
#management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoint.health.group.external-services.include=service1,service2


spring.profiles.active=diwali, christmas